[package]
name = "supermarket-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.12", features = ["gzip", "json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
futures = "0.3.25"
sqlx = { version = "0.6.2", features = [
	"postgres",
	"runtime-tokio-native-tls",
] }
dotenvy = "0.15.6"
error-stack = "0.2.4"
