version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.database
    restart: always
    environment:
      # these parameters may be set in .env file, or through normal env setting
      # commands
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
